### ISSUE TITLE
Why using "-hotrunner"

### ISSUE THREAD

**Issue by PalashBansal** [blackberry/BlackBerry-Communication-Services-Examples#11]
My sincere apologies for raising this irrelevant issue here but as https://github.com/blackberry/CppUnit repo is read-only, i could find a way to put this doubt I have.

I am using cppUnit in one of my application as a tester and found that it(.exe) loads .dll and makes it's copy in the name of something.dll-hotrunner (-hotrunner suffix) but couldn't find reason to do so.
https://github.com/blackberry/CppUnit/blob/48e34edb16a9c2860368901577a9b5f22d88e823/src/msvc6/testpluginrunner/TestPlugIn.cpp#L25 for better understanding.
Can anyone please enlighten me about why seperate -hotrunner copy is created instead of using the original dll?

**Comment by PalashBansal** [comment]
https://github.com/hungc Can you please clear this doubt?

**Comment by JeffinWithYa** [comment]
Hi @PalashBansal , my apologies, but we are no longer maintaining repos for development on the BlackBerry Playbook or other BB OS or BB10  devices. I will be closing this issue.
